apiVersion: v1
kind: Service
metadata:
  name: solar-system
  namespace: ${NAMESPACE}
  labels:
    app: solar-system
spec:
  selector:
    app: solar-system
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer

