name: Deploy GA Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/ga-application:${{ github.sha }}

      - name: Install envsubst
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Replace placeholders in YAML files
        run: |
          export IMAGE="${{ vars.DOCKERHUB_USERNAME }}/ga-application:${{ github.sha }}"
          export NAMESPACE="${{ vars.NAMESPACE }}"
          export REPLICAS="${{ vars.REPLICAS }}"
          envsubst < kubernetes/production/deployment.yaml > kubernetes/production/deployment.generated.yaml
          envsubst < kubernetes/production/service.yaml > kubernetes/production/service.generated.yaml

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.26.3/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
          kubectl config current-context

      - name: Create Kubernetes namespace (if not exists)
        run: |
          kubectl create ns ${{ vars.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Create MongoDB secret
        run: |
          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ vars.MONGO_URI }} \
            --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
            --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/production/deployment.generated.yaml
          kubectl apply -f kubernetes/production/service.generated.yaml
          kubectl get all -n ${{ vars.NAMESPACE }}

