name: Deploy GA Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/ga-application:${{ github.sha }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.26.3/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          export KUBECONFIG=~/.kube/config
          kubectl config use-context minikube

      - name: Test kubectl connection
        run: |
          kubectl get nodes
          kubectl get namespaces

      - name: Replace variables in manifests
        run: |
          sed -i "s|\$IMAGE|${{ vars.DOCKERHUB_USERNAME }}/ga-application:${{ github.sha }}|g" kubernetes/production/deployment.yaml
          sed -i "s|\$NAMESPACE|${{ vars.NAMESPACE }}|g" kubernetes/production/deployment.yaml
          sed -i "s|\$REPLICAS|${{ vars.REPLICAS }}|g" kubernetes/production/deployment.yaml
          sed -i "s|\$NAMESPACE|${{ vars.NAMESPACE }}|g" kubernetes/production/service.yaml

      - name: Create Kubernetes namespace (if not exists)
        run: |
          kubectl create ns ${{ vars.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Create MongoDB secret
        run: |
          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ vars.MONGO_URI }} \
            --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
            --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/production/
          kubectl get all -n ${{ vars.NAMESPACE }}

