name: Deploy GA Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/ga-application:${{ github.sha }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: '1.26.0'

    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Replace tokens in YAML
      uses: hugoalh/token-replace-ghaction@v2.0.3
      with:
        files: |
          kubernetes/production/deployment.yaml
          kubernetes/production/service.yaml
        token: "_{_{key}_}_"
        replace: |
          NAMESPACE=${{ vars.NAMESPACE }}
          REPLICAS=${{ vars.REPLICAS }}

    - name: Create MongoDB secret
      run: |
        kubectl create ns ${{ vars.NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
        kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
        --from-literal=MONGO_URI=${{ vars.MONGO_URI }} \
        --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
        --from-literal=MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }} \
        --dry-run=client -o yaml | kubectl apply -f -

    - name: Apply manifests
      run: |
        kubectl apply -f kubernetes/production/
        kubectl get all -n ${{ vars.NAMESPACE }}

