name: CI/CD Pipeline for Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Push Docker Image & Deploy to K8s
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: shadyemad2/ga-application:${{ github.sha }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Push Docker image to Docker Hub
      run: docker push $IMAGE_NAME

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.29.0

    - name: Create kubeconfig file
      run: echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig.yaml

    - name: Deploy to Kubernetes cluster
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
      run: |
        kubectl config use-context minikube
        kubectl apply -f kubernetes/production/

